### ISSUE TITLE
Edgar Axel Sandoval Hernández 

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-2-infografia-EdgarExa#3]
[INFOGRAFÍA  fundamentos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-EdgarExa/files/9532288/INFOGRAFIA.fundamentos.pdf)

INFOGRAFÍA
Grupo 1BS

**Comment by josealfredo79** [comment]
Falta la calificacion....

**Comment by josealfredo79** [comment]
Falta nuevamente calificar

**Comment by josealfredo79** [comment]
Falta que evaluen este trabajo...

**Comment by MarleneRamirez0731** [comment]
17% según la rúbrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
